apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: my-vm-pool
  annotations:
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /spec/replicas
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io/vmpool: my-vm-pool
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: my-vm-pool
    spec:
      running: true
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: my-vm-pool
        spec:
          domain:
            devices:
              disks:
              - disk:
                  bus: virtio
                name: containerdisk
            resources:
              requests:
                memory: 128Mi
          terminationGracePeriodSeconds: 0
          volumes:
          - containerDisk:
              image: kubevirt/cirros-container-disk-demo:latest
            name: containerdisk
